### ISSUE TITLE
MAINT: rename or remove _model_params

### ISSUE THREAD

**Issue by adriangb** [adriangb/scikeras#107]
`BaseWrapper._model_params` is currently not used by SciKeras and is not public. We should either:
1. Rename it and make it public if it is useful to users.
2. Remove it.

**Comment by stsievert** [comment]
Here's where `_model_params` is defined:

https://github.com/adriangb/scikeras/blob/5ed2646a33a95564bf38f68279ddd1bfecffd5a7/scikeras/wrappers.py#L188-L195

I think a third option:

3. Keep the same name but use it. I would imagine it's useful in `_fit` somewhere.

**Comment by adriangb** [comment]
It turns out we do use it, I just did't catch it because it's inside a `getattr`:
https://github.com/adriangb/scikeras/blob/5ed2646a33a95564bf38f68279ddd1bfecffd5a7/scikeras/wrappers.py#L301-L305

I think we need to:
1. Change `pass_filter=getattr(self, "_user_params", set())` -> `pass_filter=self._user_params`
2. Remove [this](https://github.com/adriangb/scikeras/blob/9f633f5c21a45b43986a8d779c3ef9e3005038bb/tests/test_param_routing.py#L117-L121) test.
