### ISSUE TITLE
DOC: the override methods for handling multiple input seems to be misspelled 

### ISSUE THREAD

**Issue by gioxc88** [adriangb/scikeras#136]
Reading the documentation [here](https://scikeras.readthedocs.io/en/latest/advanced.html?highlight=multiple#data-transformers) it says :

To override the default transformers, simply override `scikeras.wrappers.BaseWrappers.target_transformer()` or `scikeras.wrappers.BaseWrappers.function_transformer()` for `y` and `X` respectively.

I believe this should be `scikeras.wrappers.BaseWrappers.target_encoder` or `scikeras.wrappers.BaseWrappers.feature_encoder` for `y` and `X` respectively, instead.

**Comment by adriangb** [comment]
You are right! I'll get that fixed, thank you for reporting it.
