### ISSUE TITLE
Scorer in BaseWrapper should accept y_true and y_pred instead of X and y

### ISSUE THREAD

**Issue by data-hound** [adriangb/scikeras#168]
As per the documentation for the scorer function in BaseWrapper:

> Parameters
        ---------- 
        y_true : array-like of shape (n_samples,) or (n_samples, n_outputs)
            True labels.
        y_pred : array-like of shape (n_samples,) or (n_samples, n_outputs)
            Predicted labels.
        **kwargs: dict
            Extra parameters passed to the scorer.

I think, the definition should be changed as:

> @staticmethod
    def scorer(y_true, y_pred, **kwargs) -> float:

 
Instead of the present definition? Or, is there a reason for such nomenclature? :
> @staticmethod
    def scorer(X, y, **kwargs) -> float:

**Comment by adriangb** [comment]
You are totally right! Will get this fixed
