### ISSUE TITLE
Extra packages listed in dependencies

### ISSUE THREAD

**Issue by stsievert** [adriangb/scikeras#212]
Why are the packages required to build the documentation listed under the dependencies?

https://github.com/adriangb/scikeras/blob/d1a9d125f627e18e68c79f1e5bf186488006da60/pyproject.toml#L31-L45

Yes, they're optional (which is good). But only devs build docs. Why not list ipykernel/jupyter/etc there?

**Comment by adriangb** [comment]
The only reason is that then if you don't plan on building docs, you still end up with a ton of extra stuff installed, which is not the end of the world, but not great either. Ideally, we'd want it to be dev _and_ extras, but that's not possible, so I originally settled for it being an extra. The name of the extra, `dev_docs` makes it pretty clear that it's for developers.

But I am open to the idea of just moving it to be regular dev deps.

**Comment by stsievert** [comment]
Somewhat relevant: https://github.com/adriangb/scikeras/pull/210#discussion_r587992517
