### ISSUE TITLE
Support to Python 3.9 ?

### ISSUE THREAD

**Issue by lviano** [adriangb/scikeras#223]
Hello,

thanks a lot for your work!

While installing scikeras I noticed that Python 3.9 it is currently not supported. I was wondering if you plan to support it in future.

Thanks in advance!

All the best,
Luca

**Comment by adriangb** [comment]
Hi!

We can only support Python versions supported by our dependencies. That said, I don't see any reason why we can't unpin the version and allow it to fail based on the deps. I'll make a PR for that.

**Comment by adriangb** [comment]
@lviano let me know if this resolves the issue for you, if not we can reopen!
