### ISSUE TITLE
Transformed target regressor support?

### ISSUE THREAD

**Issue by no-clue-what-to-do** [adriangb/scikeras#235]
When I build a pipeline where I use a scikeras KerasRegressor, but put it inside of a scikitlearn [transformedtargetregressor](https://scikit-learn.org/stable/modules/generated/sklearn.compose.TransformedTargetRegressor.html), I can no longer access the training history. 

I can still access the KerasRegressor object, and when I do I get the following:
```
In [38]: pipeline['NN_model'].regressor
Out[38]: 
KerasRegressor(
	model=<function build_regressor_model at 0x000001DE15A4D5E0>
	build_fn=None
	warm_start=False
	random_state=None
	optimizer=<tensorflow.python.keras.optimizer_v2.adam.Adam object at 0x000001DE760DAF40>
	loss=mse
	metrics=None
	batch_size=None
	validation_batch_size=None
	verbose=1
	callbacks=None
	validation_split=0.2
	shuffle=True
	run_eagerly=False
	epochs=100
	parameters={'num_nodes': (250, 150, 100), 'num_dense_layers': 3, 'dropout': 0.01, 'dropout_type': 'none', 'activation': 'elu', 'output_activation': 'linear', 'learning_rate': 0.0001, 'input_dim': 258, 'output_dim': 140, 'loss': 'mse', 'epochs': 100}
)
```

but when I try to get the history object, I get the following

```
In [39]: pipeline['NN_model'].regressor.history
Traceback (most recent call last):

  File "<ipython-input-40-eb7647671dbe>", line 1, in <module>
    pipeline['NN_model'].regressor.history

AttributeError: 'KerasRegressor' object has no attribute 'history'
```

Am I doing something wrong, or is some of the functionality of scikeras not supported when using a Transformed target regressor?

**Comment by stsievert** [comment]
Try `history_`, not `history`.

https://github.com/adriangb/scikeras/blob/7c072fbed1985e9ad58e2291b3fee2324e4c39ea/scikeras/wrappers.py#L94-L95

**Comment by adriangb** [comment]
If you are coming from the TensorFlow wrappers, I'd also suggest you check out our [migration guide](https://www.adriangb.com/scikeras/stable/migration.html#) for some other subtle changes.

**Comment by no-clue-what-to-do** [comment]
Oh, sorry, that was a typo above. It still doesn't work with history_

I have some model where I don't transform the target data and all the scikeras functionality works super well. It's just when I wrap the regressor in a transformedtargetregressor when I have issues.

I tried using the following line in the migration guide, but got an error
hist = clf.fit(...).history_

AttributeError: 'Pipeline' object has no attribute 'history_'

**Comment by adriangb** [comment]
> It still doesn't work with history_

Could you help is with the error you are getting?

I think you'd want to do:

```python
pipeline['NN_model'].history_
```

**Comment by no-clue-what-to-do** [comment]
So, my pipeline is as follows:

```
Pipeline(memory=None,
         steps=[('preprocess', MinMaxScaler(copy=True, feature_range=(0, 1))),
                ('NN_model',
                 TransformedTargetRegressor(check_inverse=True, func=None,
                                            inverse_func=None,
                                            regressor=KerasRegressor(batch_size=None, build_fn=None, callbacks=None, epochs=100, loss='mse', metrics=None, model=<function build_regressor_model at 0x000001DE1D4073A0>, optimizer=<ten...': 100, 'input_dim': 258, 'learning_rate': 0.0001, 'loss': 'mse', 'num_dense_layers': 3, 'num_nodes': (250, 150, 100), 'output_activation': 'linear', 'output_dim': 140}, random_state=None, run_eagerly=False, shuffle=True, validation_batch_size=None, validation_split=0.2, verbose=1, warm_start=False),
                                            transformer=MinMaxScaler(copy=True,
                                                                     feature_range=(0,
                                                                                    1))))],
```

If I do pipeline['NN_model'], it will return a scikitlearn TransformedTargetRegressor object, like this
```
TransformedTargetRegressor(check_inverse=True, func=None, inverse_func=None,
                           regressor=KerasRegressor(batch_size=None, build_fn=None, callbacks=None, epochs=100, loss='mse', metrics=None, model=<function build_regressor_model at 0x000001DE1D4073A0>, optimizer=<tensorflow.python.keras.optimizer_v2.adam.Adam object at 0x000001DE1ABDFAC0>, parameters={'activation': 'el...e': 'none', 'epochs': 100, 'input_dim': 258, 'learning_rate': 0.0001, 'loss': 'mse', 'num_dense_layers': 3, 'num_nodes': (250, 150, 100), 'output_activation': 'linear', 'output_dim': 140}, random_state=None, run_eagerly=False, shuffle=True, validation_batch_size=None, validation_split=0.2, verbose=1, warm_start=False),
                           transformer=MinMaxScaler(copy=True,
                                                    feature_range=(0, 1)))
```

This object does not have a hitory_ attribute. however, if I type pipeline['NN_model'].regressor, I get the actual scikeras regresor object, like this
```
KerasRegressor(
	model=<function build_regressor_model at 0x000001DE1D4073A0>
	build_fn=None
	warm_start=False
	random_state=None
	optimizer=<tensorflow.python.keras.optimizer_v2.adam.Adam object at 0x000001DE1ABDFAC0>
	loss=mse
	metrics=None
	batch_size=None
	validation_batch_size=None
	verbose=1
	callbacks=None
	validation_split=0.2
	shuffle=True
	run_eagerly=False
	epochs=100
	parameters={'num_nodes': (250, 150, 100), 'num_dense_layers': 3, 'dropout': 0.01, 'dropout_type': 'none', 'activation': 'elu', 'output_activation': 'linear', 'learning_rate': 0.0001, 'input_dim': 258, 'output_dim': 140, 'loss': 'mse', 'epochs': 100}
)
```

Normally, when I type .history_ after a trained scikeras model, I get the recorded history of the losses, but when it is wrapped in the TransformedTargetRegressor object, it doesn't exist. Does that help clarify things?

I know there are some workarounds. I could define my own custom class to transform the y data and then do an inverse transform, but then I'm losing many of the benefits of scikeras, because I could save the history object on my own, and can't save everything in one clean pipeline. If there is a different workaround I haven't thought of that does use a TransformedTargetRegressor and doesn't use custom classes, I'd love to hear it, but I also think it would be nice if scikeras objects still worked when using this very helpful function

**Comment by no-clue-what-to-do** [comment]
here is a standalone example that reproduces the problem:

```
from tensorflow import keras

from keras.layers import Dense, Conv1D, Reshape, Dropout,Flatten, concatenate, Activation, LeakyReLU#,GaussianNoise
from keras import optimizers
from keras.engine.sequential import Sequential
# from keras.wrappers.scikit_learn import KerasRegressor
from keras import backend as K
from keras.layers.core import Lambda


# from keras.wrappers.scikit_learn import KerasRegressor
from scikeras.wrappers import KerasRegressor
from sklearn.pipeline import Pipeline
from sklearn.compose import TransformedTargetRegressor
from sklearn.preprocessing import StandardScaler, MinMaxScaler

import numpy as np


def build_regressor_model(parameters):

    input_layer = keras.Input(shape=(parameters['input_dim'],),name='input')

    layer = input_layer
    for i in range(parameters['num_dense_layers']):
        num_dense_nodes = parameters['num_nodes'][i]
                                 
        layer = Dense(num_dense_nodes, activation=parameters['activation'],  name='fc_'+str(i))(layer)
        
        if parameters['dropout_type'] == 'Permadropout':
            layer = Dropout(parameters['dropout'],  name='dropout_'+str(i))(layer)
        elif parameters['dropout_type'] == 'dropout':
            layer = Dropout(parameters['dropout'],  name='dropout_'+str(i))(layer)
    
    outputs = Dense(parameters['output_dim'], activation=parameters['output_activation'])(layer)

    model = keras.Model(inputs=input_layer, outputs=outputs)

    # model.compile(loss=parameters['loss'], optimizer=optimizers.Adam(lr=parameters['learning_rate']))
 
    return model      


x = np.random.rand(100,100)
y = np.random.rand(100,100)


parameters = {'num_nodes' : (250, 150, 100), 
              'num_dense_layers': 3, 
              'dropout': 0.01, 
              'dropout_type': 'none',
              'activation': 'elu',
              'output_activation': 'linear',
              'learning_rate': .0001,
              'input_dim': x.shape[1],
              'output_dim': y.shape[1],
               'loss':'mse',
              'epochs':100}


NN = KerasRegressor(model=build_regressor_model, 
                    validation_split=.2,
                    loss=parameters['loss'],
                    # metrics=['val_loss'],
                    optimizer=optimizers.Adam(lr=parameters['learning_rate']),
                    verbose=0,
                    epochs=parameters['epochs'], 
                    parameters=parameters) 


NN_model_with_y_scaling = TransformedTargetRegressor(regressor=NN,transformer=MinMaxScaler()) 
    
pipeline = Pipeline([
    ('preprocess',StandardScaler()),
    ('NN_model',NN_model_with_y_scaling)])

pipeline['NN_model'].regressor.history_



#without TTR
# pipeline = Pipeline([
#     ('preprocess',StandardScaler()),
#     ('NN_model',NN)])        
# pipeline.fit(x, y)

# pipeline['NN_model'].history_
```

**Comment by no-clue-what-to-do** [comment]
The behavior is really weird. If I train a model in a fresh kernal with TTR, then I can't display a history object. BUT, if I first train a model without TTR, then train a different model with TTR, I can print the history object! I dont understand this at all. To make it a little clearer, here are the two cases below

Case 1 (Can't print history object)
-Fit pipeline with TTR
-Try to print pipeline['NN_model'].regressor.history_
-Get error message saying object doesn't exist

Case 2
-Fit pipeline without TTR
-Succesfully print pipeline['NN_model'].history_
-Fit pipeline_2 with TTR (different name, same input vars)
-Try to print pipeline_2['NN_model'].regressor.history_
-Somehow succeeds! With the same values as pipeline['NN_model'].history_


Any clue why this is happening?

**Comment by no-clue-what-to-do** [comment]
Ok, actually figured that last question out already. Both pipeline were sharing the same NN object. When it is trained with TTR, the history_ object is not created, but when it is trained without TTR, the history_ object is created and seem to stay in place when using the NN object in a different pipeline, even when refitting

**Comment by adriangb** [comment]
Aha! I _think_ I found the problem:

https://github.com/scikit-learn/scikit-learn/blob/2beed55847ee70d363bdbfe14ee4401438fba057/sklearn/compose/_target.py#L205

Scikit-Learn clones the regressor and saves it under `regressor_` before fitting. So when you access `.regressor` you are accessing an un-fitted copy of the regressor, which has 0 trained epochs and hence no `history_` attribute.

Try:

```
pipeline['NN_model'].regressor_.history_
```

**Comment by no-clue-what-to-do** [comment]
That worked! Thank you so much!

**Comment by adriangb** [comment]
Glad we could help!
