### ISSUE TITLE
missing dependencies: packaging

### ISSUE THREAD

**Issue by sim-san** [adriangb/scikeras#246]
I get this error with new version 0.4.0
```
  File "/builds/optim_lib/optimization_library/models/base_model.py", line 3, in <module>
    from scikeras.wrappers import KerasRegressor
  File "/builds/optim_lib/venv/lib/python3.7/site-packages/scikeras/__init__.py", line 16, in <module>
    from packaging import version
ModuleNotFoundError: No module named 'packaging'
```

I solved this by adding `packaging==21.0` to my requirements file.

**Comment by adriangb** [comment]
Thank you @sim-san !

I'm not sure why this isn't an issue in CI or locally for me, I guess the package just tends to be installed globally... I'll cut a release soon w/ the fix.
