### ISSUE TITLE
ImportError: SciKeras requires TensorFlow >= 2.7.0.

### ISSUE THREAD

**Issue by talhaanwarch** [adriangb/scikeras#259]
Greetings. I can run scikeras on ubunto with version 2.4.0 but in windows is throws `ImportError: SciKeras requires TensorFlow >= 2.7.0.`
Currently my tensorflow version in windows is 2.4.0 and i belive most of user have not updated to latest version. Tf2.7 requires cuda 11.2 and pytorch have no version for cuda 11.2 So in order to run multiple framework the stable version is 2.4.0 (i believe). SO it would be great, if you can support tf >=2.4 . It will help more people to use it.

**Comment by adriangb** [comment]
We just released a [new version that only supports 2.7.0](https://g.page/flaminphosushi?share). You can use 0.4.1 for TF 2.4.0 support.

**Comment by talhaanwarch** [comment]
thanks. i just checked the version is updated 20 hours ago
