### ISSUE TITLE
tensorflow should be a main dependency (instead of a dev dependency)

### ISSUE THREAD

**Issue by metasyn** [adriangb/scikeras#261]
I am trying to use `scikeras` in a poetry based project. I ran

```
poetry add scikeras
```
which worked. At runtime, I got an error saying that tensorflow 2.7.0 was needed. This should've been caught at the time I added the package during poetry. The only reason, from my understanding that it wasn't was because tensorflow is a dev dependency, rather than a real dependency, for poetry.

**Comment by adriangb** [comment]
This is a known issue, and stems from a limitation of how TensorFlow packages itself. The TLDR is that there are other versions of tensor flow like `tensorflow-cpu`, so if we specified `tensorflow` as a hard dependency users who want to use `tensorflow-cpu` wouldn't be able to install SciKeras. For more background, see https://github.com/adriangb/scikeras/issues/221.

**Comment by metasyn** [comment]
Ah, I see. 

https://github.com/adriangb/scikeras/issues/221#issuecomment-805034870

I think option 1 here is a bit cleaner, but makes sense to go either way to solve the problem. No worries if you just want to close this, I should've read the readme closer. Thanks for the cool package :)

**Comment by adriangb** [comment]
Yeah I guess we can make TensorFlow an optional dependency and the update everywhere in the documentation to use `scikeras[tensorflow]` so that at least users copy pasting from the readme won't get caught off guard that easily. A PR for something like this would be gladly accepted :)

**Comment by metasyn** [comment]
I see. What do you think of adding both?

```
poetry add --optional tensorflow==2.7.0
poetry add --optional tensorflow-cpu==2.7.0
```
?
