### ISSUE TITLE
The documentation website is down

### ISSUE THREAD

**Issue by Lucylucy712** [adriangb/scikeras#268]
I am trying to check the documentation site. However, it's unavaiable with error below.  

This site can’t be reachedThe webpage at https://www.adriangb.com/scikeras/ might be temporarily down or it may have moved permanently to a new web address.
ERR_TUNNEL_CONNECTION_FAILED

**Comment by adriangb** [comment]
It seems to work fine for me. Would you mind checking another network?

**Comment by adriangb** [comment]
Hi since I haven't been able to reproduce this, I think this is an issue on your end. Please let me know if you have any further info.
