### ISSUE TITLE
support python 3.10 ?

### ISSUE THREAD

**Issue by jeffery9876** [adriangb/scikeras#273]
Hi, 

with the latest `tensorflow 2.8` and sklearn already supporting `python 3.10`, I believe it's time to loose the project constrain to support 3.10? 

https://github.com/adriangb/scikeras/blob/962776ae6ffa2e77bffdf320067bba1d62905524/pyproject.toml#L33

Is there anything else holding back this ?

Many thanks

**Comment by adriangb** [comment]
Indeed. We also need to add 3.10 to CI. Are you interested in making the PR? No problem if not, I just want to give you the chance since you brought it up 😁

**Comment by jeffery9876** [comment]
Thanks Adrian. PR submitted
