### ISSUE TITLE
adriangb.com/scikeras is DOWN

### ISSUE THREAD

**Issue by smith558** [adriangb/scikeras#294]
https://adriangb.com/scikeras/
![image](https://user-images.githubusercontent.com/44023416/229369998-1745d4d1-23e6-473c-8077-cca46b696a91.png)

**Comment by adriangb** [comment]
Should be back up. Can you confirm?

**Comment by smith558** [comment]
Works now. 🙂 May I ask, is this project still actively maintained? (and perhaps planned to be, for the near future)

**Comment by adriangb** [comment]
The page being down had nothing to do with the projects maintenance, I was just doing some re-arranging of my GitHub pages.

I'm not planning on adding extensive new feature or any time soon, but I have been keeping the project up to date with TensorFlow releases and such. Is there anything missing that makes you ask that?

**Comment by smith558** [comment]
No worries! The question was not necessarily related. I just like to know whether projects are maintained before I decide to further study the documentation and perhaps use it in my models.
