### ISSUE TITLE
How to use the wrappers function in onnx?

### ISSUE THREAD

**Issue by praneeth5222** [adriangb/scikeras#296]
Hello @adriangb 

Can you guide me in using [KerasClassifier](https://adriangb.com/scikeras/stable/generated/scikeras.wrappers.KerasClassifier.html) in [ONNX runtime](https://onnxruntime.ai/)?

**Comment by adriangb** [comment]
That's a bit general of a question. Models ran via ONNX are no longer TensorFlow models I think, so SciKeras would not be compatible with them (that is, SciKeras can't wrap an ONNX model)

**Comment by praneeth5222** [comment]
Thank you @adriangb for your quick response.
Tensorflow models can be converted to ONNX using [tf2onnx](https://github.com/onnx/tensorflow-onnx) module but I'm unable to find a module to convert a scikeras class to ONNX

**Comment by adriangb** [comment]
SciKeras is just a shimmy between scikit learn models and tensorflow models. I'd recommend you convert the actual tensorflow model to ONNX. SciKeras is not in and of itself a machine learning framework.

**Comment by praneeth5222** [comment]
Got it!!
Thank you.

**Comment by praneeth5222** [comment]
I know I have closed this thread @adriangb  just wanted your suggestion if you have any for the problem I'm facing with

So i have a Keras model that I wanted to use along with sklearn [CalibratedClassifierCV](https://scikit-learn.org/stable/modules/generated/sklearn.calibration.CalibratedClassifierCV.html) to calibrate the probability outputs and convert the entire pipeline to ONNX.

Since keras model doesn't have **predict_proba** method inbuilt which is a requirement for CalibratedClassifierCV; I have tried to use [KerasClassifier](https://adriangb.com/scikeras/stable/generated/scikeras.wrappers.KerasClassifier.html) to wrap the keras model so that I can use it for calibration but then if I do so I'm not able to convert the pipeline to ONNX because of the **KerasClassifier**

Any thoughts or suggestions here?

**Comment by praneeth5222** [comment]
>  Could you export just the TensorFlow model and re-create your sklearn pipeline when you want to do inference and use it as a transformer?

Do you mind explaining this, when you say recreating your sklearn pipeline?
Here I do want to recalibrate the prediction probabilities from the Tensorflow Keras model every time the model train happens and use them both in the runtime using ONNX

**Comment by ghost** [comment]
Hi @adriangb 
I have stumbled on this issue once again. Can you explain the above-said statement?
