### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by PierreGtch** [adriangb/scikeras#304]
Hi,
Thanks for this library. 
How do you prefer it to be cited from a scientific article?

See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by adriangb** [comment]
Oh cool! Please use my full name (Adrian Garcia Badaracco) and “Pydantic” as the institution. Cc @stsievert if you would like to be cited as well.
