### ISSUE TITLE
OneHotEncoder no longer uses `sparse` keyword

### ISSUE THREAD

**Issue by ashokrajaraman** [adriangb/scikeras#319]
Line 170 in `utils/transformers.py` uses OneHotTransformer using the keyword `sparse`. This has been changed to `sparse_output` since version 1.2 of scikit-learn.

https://github.com/adriangb/scikeras/blame/9ec5ca6fbebaa00c98ba52c8c56d4e7355efabb5/scikeras/utils/transformers.py#L170

Documentation for reference:

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

**Comment by adriangb** [comment]
Yes an update to this library is needed, this has laready been reported

**Comment by adriangb** [comment]
Could you please try #317 (`pip install -U 'git+https://github.com/adriangb/scikeras.git@keras-3'`) and see if it fixes your problem? Thanks!

**Comment by adriangb** [comment]
This should be fixed now. Please let me know if this is still not fixed with SciKeras 0.13.0. Thanks!
