### ISSUE TITLE
Multi-backend scikeras (Tensorflow, Jax, Pytorch)

### ISSUE THREAD

**Issue by mthiboust** [adriangb/scikeras#324]
Thanks @adriangb for this library!

I see that the new `keras 3`-compatible `scikeras 0.13.0` still relies on `tensorflow`. Now that `keras 3` is backend-agnostic, do you have any plan on making `scikeras` backend-agnostic as well? It would be great to use the Pytorch or JAX backend.

**Comment by adriangb** [comment]
Does it? It’s an optional dependency: https://github.com/adriangb/scikeras/blob/e92a7dc466cef81b041740978cc047594fea6b4d/pyproject.toml#L35

**Comment by mthiboust** [comment]
Nice to hear, thanks! I thought it wasn't because I saw tensorflow-specific code to handle the `random_state` in 
https://github.com/adriangb/scikeras/blob/master/scikeras/utils/random_state.py 

Closing the issue
