### ISSUE TITLE
Extracting the underlying Keras model from the wrapper

### ISSUE THREAD

**Issue by msabanluc** [adriangb/scikeras#326]
Hi,
I'm wondering if it is possible to extract the underlying model from the wrapper. Something like `model = wrapper.model_` ?
I'm trying to use the Shap DeepExplainer and it currently doesn't have support for KerasClassifier, so I'm wondering if there's potentially some workaround.

**Comment by adriangb** [comment]
I think that already works?

**Comment by msabanluc** [comment]
Hi, my apologies (and thank you for the quick response)-- I realized it was an issue with my IDE not showing the variable in the variable explorer. This does work!
