### ISSUE TITLE
Keras.root_mean_squared_error is misnamed

### ISSUE THREAD

**Issue by stsievert** [adriangb/scikeras#61]
The documentation of `KerasRegressor.root_mean_square_error`: https://github.com/adriangb/scikeras/blob/d9f58336fb15fa00e04587d49d1636968d47ebfb/scikeras/wrappers.py#L997-L1002

"R^2" is the [coefficient of determination][2], not the (root) [mean squared error (MSE)][1].

The implementation even mirrors [the Wikipedia definition of R^2][3] down to the names and subscripts:

https://github.com/adriangb/scikeras/blob/d9f58336fb15fa00e04587d49d1636968d47ebfb/scikeras/wrappers.py#L1004-L1010

[1]:https://en.wikipedia.org/wiki/Mean_squared_error
[2]:https://en.wikipedia.org/wiki/Coefficient_of_determination
[3]:https://en.wikipedia.org/wiki/Coefficient_of_determination#Definitions

**Comment by adriangb** [comment]
You are absolutely right! I will fix this ASAP.
