### ISSUE TITLE
conda environment - pip install - scipy 1.4.1 dependency 

### ISSUE THREAD

**Issue by dpatschke** [adriangb/scikeras#71]
First off, thanks for your efforts with the development of this package!

I wanted to point out something that I noticed on install. I'm wanting to 'pip install' within a conda environment and was hoping the only dependencies I needed to worry about were documented in the pyproject.toml file in the [tool.poetry.dependencies] section so that pip didn't overwrite any of the conda-managed packages. 

It appears there is some other dependency that is causing a forced load of scipy 1.4.1. I had scipy 1.5.2 installed in my conda environment but pip forced an uninstall of that version.

Any ideas what package may be causing this and/or how to get around this?

**Comment by adriangb** [comment]
I tried this in a clean virtual env:
```bash
pip install scipy==1.5.2
pip freeze | grep scipy  # lists scipy==1.5.2
pip install tensorflow
pip freeze | grep scipy  # lists scipy==1.4.1
```
So it looks like tensorflow is what is forcing the downgrade.

The best I can suggest is to install scikeras and _then_ install your scipy version.

**Comment by dpatschke** [comment]
Thanks for the quick reply! That is weird ... I received this message during the scikeras install:

> Requirement already satisfied: tensorflow>=2.1.0 in .........../lib/python3.7/site-packages (from scikeras) (2.2.0)

So even though the dependency is met for tensorflow, pip still tries to load other tensorflow dependencies? Uggh ... pip.

**Comment by adriangb** [comment]
If you already have scikit-learn and tensorflow installed, and have figured out all versions, you could do `pip install scikeras --no-deps`

**Comment by dpatschke** [comment]
Thanks! Yeah ... will do that. Probably need to get more versed in pip. I try to use conda as much as possible for reasons such as this. Closing issue!
