### ISSUE TITLE
Keras pickle RFC

### ISSUE THREAD

**Issue by stsievert** [adriangb/scikeras#77]
I'd like to help with the Keras pickle RFC that's mentioned in https://github.com/tensorflow/tensorflow/pull/39609#issuecomment-685869003. I see you have a repo https://github.com/adriangb/community. Could you create a PR internal to that repo to provide a channel to work on the draft RFC?

**Comment by adriangb** [comment]
Yes, I will do that. I started writing the doc and got only like 3 lines in. Since you plan on helping I'll post it as is in a draft PR and give you write access to the repo.

**Comment by adriangb** [comment]
PR set up at https://github.com/tensorflow/community/pull/286. Thank you for offering to help @stsievert !

**Comment by adriangb** [comment]
Closing this here since the discussion is not scikeras specific and should be visible in the tf/tf community repos.
