### ISSUE TITLE
Clarification: difference between _keras_build_fn arguments and instance attributes 

### ISSUE THREAD

**Issue by gioxc88** [adriangb/scikeras#80]
Following the example below taken from the documentation

```
from scikeras.wrappers import KerasRegressor


class MLPRegressor(KerasRegressor):

    def __init__(self, hidden_layer_sizes=None):
        self.hidden_layer_sizes = hidden_layer_sizes

    def _keras_build_fn(self, meta, hidden_layer_sizes):
        """Dynamically build regressor."""
        if hidden_layer_sizes is None:
            hidden_layer_sizes = (100, )
        model = Sequential()
        model.add(Dense(meta["X_shape_"][1], activation="relu", input_shape=meta["X_shape_"][1:]))
        for size in hidden_layer_sizes:
            model.add(Dense(size, activation="relu"))
        model.add(Dense(meta["n_outputs_"]))
        model.compile("adam", loss=KerasRegressor.r_squared)
        return model
```

Why do I need to specify the hidden layer size as an argument for the _keras_build_fn?
Is there any difference between the above and the following implementation?
I removed the `hidden_layer_size` parameter from the `_keras_build_fn` since it is already present as instance attribute.
Is there anything I did not consider which make the first implementation better? 
I general if I choose to go with the subclassing pattern why do I need to specify additional arguments for the `_keras_build_fn` other than `meta`?

```
from scikeras.wrappers import KerasRegressor


class MLPRegressor(KerasRegressor):

    def __init__(self, hidden_layer_sizes=(100, )):
        self.hidden_layer_sizes = hidden_layer_sizes

    def _keras_build_fn(self, meta):
        """Dynamically build regressor."""
 
        hidden_layer_sizes = self.hidden_layer_sizes

        model = Sequential()
        model.add(Dense(meta["X_shape_"][1], activation="relu", input_shape=meta["X_shape_"][1:]))
        for size in hidden_layer_sizes:
            model.add(Dense(size, activation="relu"))
        model.add(Dense(meta["n_outputs_"]))
        model.compile("adam", loss=KerasRegressor.r_squared)
        return model
```

Many thanks

**Comment by adriangb** [comment]
Hi,

If you go with the subclassing pattern, you do not need to specify those arguments. The only reason to keep them is for parity with the non-subclassed pattern, where you would need to specify them. I realize this may be confusing, and will note this for when docs get overhauled.

The only thing your example is missing to work properly is a call to `super().__init__()` for cooperative inheritance:

```python3
class MLPRegressor(KerasRegressor):

    def __init__(self, hidden_layer_sizes=(100, )):
        super().__init__()
        self.hidden_layer_sizes = hidden_layer_sizes
```

**Comment by gioxc88** [comment]
> Hi,
> 
> If you go with the subclassing pattern, you do not need to specify those arguments. The only reason to keep them is for parity with the non-subclassed pattern, where you would need to specify them. I realize this may be confusing, and will note this for when docs get overhauled.
> 
> The only thing your example is missing to work properly is a call to `super().__init__()` for cooperative inheritance:
> 
> ```python
> class MLPRegressor(KerasRegressor):
> 
>     def __init__(self, hidden_layer_sizes=(100, )):
>         super().__init__()
>         self.hidden_layer_sizes = hidden_layer_sizes
> ```
> 
> I'll fix the docs to include that :)

Yes of course I forgot `super()`, thanks for pointing that out.
Anyway thanks for the answer and for the great package. This is a blessing since it works better than the original and also tf wants to deprecate the skleanr api.

If the documentation were more accurate it would be perfect
Great work

**Comment by adriangb** [comment]
This should be in the [docs](https://render.githubusercontent.com/view/ipynb?commit=86d9b04cb9cc2c30eeabbce3f5771ce3e2ff3754&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f61647269616e67622f7363696b657261732f383664396230346362396363326333306565616262636533663537373163653365326666333735342f6e6f7465626f6f6b732f4d4c50436c61737369666965725f4d4c50526567726573736f722e6970796e62&nwo=adriangb%2Fscikeras&path=notebooks%2FMLPClassifier_MLPRegressor.ipynb&repository_id=254741570&repository_type=Repository#Subclassing) now!
