### ISSUE TITLE
BUG: kwargs cannot be passed to fit method

### ISSUE THREAD

**Issue by gioxc88** [adriangb/scikeras#84]
As explained here

https://github.com/adriangb/scikeras#passing-arguments-to-keras-methods

I should be able to pass for example `epochs` directly to the `fit` method, but this raises an error:

`TypeError: fit() got an unexpected keyword argument 'epochs'` 

I can see in the source code that in fact `fit` doesn't accept keyword arguments.

**Comment by adriangb** [comment]
The `{KerasClassifier, KerasRegressor}.fit(**kwargs)` interface is being deprecated. We're in the middle of migrating from a README.md to ReadTheDocs, so yeah the README.md is getting out of date. The immediate workaround is to use option 1. in that section, i.e. `KerasClassifier(..., epochs=2)` or to be more verbose `KerasClassifier(..., fit__epochs=2)`.

**Comment by adriangb** [comment]
I'm going to close this since this is a docs issue and there is already a PR addressing docs (#73).
